name: HoYoLab 자동 출석 (오전 1시~5시)_asst

on:
  schedule:
    - cron: "26 16 * * *"   # 한국시간 01:26
    - cron: "26 17 * * *"   # 한국시간 02:26
    - cron: "6 15 * * *"   # 한국시간 05:06
    - cron: "56 20 * * *"   # 한국시간 05:56
  workflow_dispatch: {}

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: 레포 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 의존성 설치
        run: npm install

      - name: 출석 체크 실행
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          USE_LAST_AVATAR_WEBHOOK: "o"
        run: node index.js
