name: HoYoLab 자동 출석 (정각)_asst

on:
  schedule:
    - cron: "14 15 * * *"   # 한국시간 00:14
    - cron: "15 16 * * *"   # 한국시간 01:15
    - cron: "16 17 * * *"   # 한국시간 02:16
    - cron: "17 18 * * *"   # 한국시간 03:17
    - cron: "18 19 * * *"   # 한국시간 04:18
    - cron: "19 20 * * *"   # 한국시간 05:19
    - cron: "20 21 * * *"   # 한국시간 06:20
    - cron: "21 22 * * *"   # 한국시간 07:21
    - cron: "22 23 * * *"   # 한국시간 08:22
    - cron: "23 0 * * *"   # 한국시간 09:23
    - cron: "24 1 * * *"   # 한국시간 10:24
    - cron: "1 2 * * *"   # 한국시간 11:01
    - cron: "2 3 * * *"   # 한국시간 12:02
    - cron: "3 4 * * *"   # 한국시간 13:03
    - cron: "4 5 * * *"   # 한국시간 14:04
    - cron: "5 6 * * *"   # 한국시간 15:05
    - cron: "6 7 * * *"   # 한국시간 16:06
    - cron: "7 8 * * *"   # 한국시간 17:07
    - cron: "8 9 * * *"   # 한국시간 18:08
    - cron: "9 10 * * *"   # 한국시간 19:09
    - cron: "10 11 * * *"   # 한국시간 20:10
    - cron: "11 12 * * *"   # 한국시간 21:11
    - cron: "12 13 * * *"   # 한국시간 22:12
    - cron: "13 14 * * *"   # 한국시간 23:13
  workflow_dispatch: {}

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: 레포 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 의존성 설치
        run: npm install

      - name: 출석 체크 실행
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          USE_LAST_AVATAR_WEBHOOK: "o"
        run: node index.js
